[2021-06-15 19:14:33,807] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_de_prueba.prueba_python 2021-06-15T19:14:00.841118+00:00 [queued]>
[2021-06-15 19:14:33,845] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_de_prueba.prueba_python 2021-06-15T19:14:00.841118+00:00 [queued]>
[2021-06-15 19:14:33,847] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 19:14:33,849] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-15 19:14:33,850] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 19:14:33,876] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-06-15T19:14:00.841118+00:00
[2021-06-15 19:14:33,884] {standard_task_runner.py:53} INFO - Started process 2382 to run task
[2021-06-15 19:14:34,176] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_de_prueba.prueba_python 2021-06-15T19:14:00.841118+00:00 [running]> 651693a3c8b0
[2021-06-15 19:14:34,234] {logging_mixin.py:112} INFO - hello
[2021-06-15 19:14:34,236] {logging_mixin.py:112} INFO - world
[2021-06-15 19:14:34,239] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-15 19:14:34,273] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_de_prueba, task_id=prueba_python, execution_date=20210615T191400, start_date=20210615T191433, end_date=20210615T191434
[2021-06-15 19:14:43,763] {logging_mixin.py:112} INFO - [2021-06-15 19:14:43,762] {local_task_job.py:103} INFO - Task exited with return code 0
